const driver = require('../../config/db');


create_db().then(res => {
    console.log("event data end");
    driver.close();
});


async function create_db() {
    let session = driver.session();
    var writeTxResultPromise = await session.writeTransaction(async txc => {

        var query = `MERGE (e:Event { club_name : "Technovanza", title : "Smart City", description : "The word Smart City gets thrown around a lot, especially lately. But what does it really mean? It is the city of your dreams with the execution in reality, it is a near utopia where technologies can solve our problems. A Smart City has solution to our everyday inconveniences and interruptions, whether it be the early warnings for calamities or the simple alarm that goes off on the probability of security breach. It has residential, industrial, economical, transportation, energy resources and environmental sectors. Though technology is an answer to most of our problems, an ideal Smart City has the contribution of its people to make it a better place. So, if you think you have what it takes to make this world just a bit better, we at TECHNOVANZA ’19 invite you to come and play to win in Making your ideas stem into the real world and plan your very own SMART CITY.", date : "2020-12-27", prize : 20000, prerequistes : "A team should consist of minimum 2 and maximum 4 members.", coordinator : "Rushikesh Kejkar", contact : "9518506462", comments : "The team need to report on time at the venue", image_url : "" }); `
        var res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Technovanza", title : "Robowars", description : "Pick your side, wave your flags and choose your war cries, for soon the arena for the greatest machine warlord will be thrown open for the expert and the rookie alike. Unite with your inner warrior and prove your mettle as your automation takes on the beasts who have conquered the battleground. Rise through the rubble and make your efforts worth the pain. Fight for glory, fight for pride, it's time for you to take on the campaign! Get your blood rushing, your adrenaline pumping, for ladies and gentlemen, it's Robowars time!", date : "2020-12-27", prize : 240000, prerequistes : "A team may consist of a maximum of 6 participants. These participants can be from same or different institutes.", coordinator : "Vedang Mane", contact : "8898079659", comments : "Qualification of a robot to next level is subjective and totally on the decision of the judges. All the decisions taken by the judge will be final and binding to all", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Technovanza", title : "VRC", description : "The moment that marked the setting off of the trigger of the detonator of the sixth edition, has arrived for the equivalent delivery of the seventh one. With the Indian Post as the theme for the year, VRC 7.0 pays tribute to one of the most underrated, yet necessarily imperative system involved in making the lives of Indian citizens better. The clock is ticking and the deadline is set. The postal objectives are all clear, the payments have been initiated and the delivery systems are all in place. Are your bots ready to post the mail and get the first position delivered?", date : "2020-12-27", prize : 70000, prerequistes : "A team can consist of maximum 6 participants. Students from different educational institutes can form a team. ", coordinator : "Urmil Vasani", contact : "8999067739", comments : "Certificate of Participation will be awarded to all the teams", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Technovanza", title : "Aqua Battle", description : "The chief of the four armies is the AQUA 4.O ROBOT. You have to guide the chief of armies to play his moves, help the armies to reach the gates and informThorin about witchcraft of opponent’s army. While securing queen, participants are going to experience some of the tough opponents, the manner in which they manoeuvre their tiles and the way you react to their action and play your counter-move", date : "2020-12-27", prize : 15000, prerequistes : "A team can have a maximum of 4 members.", coordinator : "Utkarsha Toradmal", contact : "9082635499", comments : "Duration of the game is two minutes and The robot can hold only one army in its clamp at a time.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Technovanza", title : "Robomaze", description : "This is a heist…. a money heists!! You are in a city where you have to rob money from different places. You can’t remain stuck in here. Heist can’t be lived; it has to be timed. Complete the heist in time and run off the city by reaching the helipad before the cops catch you.", date : "2020-12-27", prize : 10000, prerequistes : "A team may consist of a maximum of 4 members. These members can be from same or different institutes", coordinator : "Riddhi Amale", contact : "9637345585", comments : "Certificate of participation will be awarded to all the teams and certificate of excellence will be given to the top three teams", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Technovanza", title : "Robosoccer", description : "FOOTBALL or SOCCER, say anything there is no difference because it’s not just a game it is an emotion. One of the world’s most popular and most played sport is once again brought by VJTI’s TECHNOVANZA in its very own ROBOSOCCER event.We present you a great platform to show your technical skills and presence of mind in a challenging environment. All you have to do is interweave your passion for the sport and your knowledge about robotics to mesmerize the crowd and compete in an exciting tournament.", date : "2020-12-27", prize : 15000, prerequistes : "Every team must have a name which must be unique. Technovanza reserves the right to reject entries from any Team whose name it deems inappropriate, offensive or conflicting", coordinator : "Rajul Bhargava", contact : "7021810883", comments : "Both the controller and the wire holder cannot be changed during the match", image_url : "" }); `
        res = await txc.run(query);


        query = `MERGE (e:Event { club_name : "Community of Coders(CoC)", title : "CWay", description : "A C way Universe the Marvel heroes can even fail! Thanos will be more powerful than the avengers.. Perform your best! Grab the infinity power stone... Better be Thanos rather being an Avenger here... C programming will be the basic strength of participants here to win the competition but power stone will be a path towards victory! Choose wisely.. Code wisely.. Bring out the evil in you! Kill it and win it!", date : "2020-12-27", prize : 8000, prerequistes : "C or C++ experience", coordinator : "Sagar Shah", contact : "9167100273", comments : "All the instructions provided by the organisers should be followed as closely as possible and any attempt to work around them should be avoided. ", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Community of Coders(CoC)", title : "JavaGuru", description : "Attention Avengers, Are you worthy of holding the Mjolnir? Can you compile a Java code without an error in the first attempt? Well there's just one Avenger who understands codes and can weild the Mjolnir. We lost him in the Infinity War and are in search for someone who can be Vision. The Mind Stone shall say 'Whosoever has the power to pass this test, if he be worthy, shall be the next Vision.'", date : "2020-12-27", prize : 8000, prerequistes : "Java programming", coordinator : "Kimaya Gaikwad", contact : "9892445543", comments : "No cheating would be tolerated.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Community of Coders(CoC)", title : "UltimateCoder", description : "Ultimate Coder is the biggest and grandest I-Code event that is help by Technovanza. It's not tough to become a coder, being an ultimate coder, on the other hand, is a different story. You will have the option of using languages like C, C++, Java and Python, but will you know how? We test not only your coding skills, but how you cope with the pressure of the challenges and tasks.", date : "2020-12-27", prize : 40000, prerequistes : "A team should have two members. The members of the team can be from different colleges. A person cannot be part of more than one team. They need to be registered only once in any team. ", coordinator : "Kimya Gaikwad", contact : "9892445543", comments : "Usage of mobile devices and/ or other smart devices is not allowed.", image_url : "" }); `
        res = await txc.run(query);


        query = `MERGE (e:Event { club_name : "Society of Robotics and Automation(SRA)", title : "Wall-E workshop", description : "The Wall-E workshop focuses on the concepts of line-following and self-balancing, using ESP32, a powerful micro-controller with features like inbuilt Wi-Fi support and BLE, with extensive application in several domains like IoT, RF, etc. The workshop entails various essential concepts such as PID Control, Embedded Communication Protocols, PWM, Filters, RTOS, etc. and gives its attendees (first-year students) a general idea about the world of robotics and embedded hardware.", date : "2020-12-27", prerequistes : "Students should be in the first year. Any branch is allowed", coordinator : "Prakash Jha", contact : "9875372845", comments : "SRA conducts two major workshops over a year with an objective to give hand-on experience to beginners so that they get into the swing of how things work and are able to build a project on their own.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Society of Robotics and Automation(SRA)", title : "MARIO workshopp", description : "The MARIO workshop (3-DOF Manipulator on ROS-based IO) is workshop by SRA, wherein freshers design and implement a robotic manipulator using intricate concepts of forward and inverse kinematics, with Robot Operating System (ROS). ROS is an industrial-based software which has application in colossal domains.", date : "2020-12-27", prerequistes : "Students should be in the first year. Any branch is allowed", coordinator : "Amrit Balani", contact : "9546273421", comments : "SRA conducts two major workshops over a year with an objective to give hand-on experience to beginners so that they get into the swing of how things work and are able to build a project on their own.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Society of Robotics and Automation(SRA)", title : "ALGOCON", description : "SRA conducts an online coding competition with problem statements on Data Structures and Algorithms chosen to exude the contestant’s sharp thinking.The top participants are chosen on the basis of the difficulty of the problem solved, and the efficacy of their solutions.", date : "2020-12-27", prize : 5000, prerequistes : "Basic understanding of Data structures and Algorithms", coordinator : "Preeet Jain", contact : "9678546372", comments : "Do your best!!", image_url : "" }); `
        res = await txc.run(query);

        query = `MERGE (e:Event { club_name : "Enthusia", title : "Pro Football League", description : "Pro Football League is VJTI's professional football league. 12 teams from Mumbai’s best colleges will compete in a league-cum-knockout format to be crowned as the inaugural PFL Champions. Not compromising on professional standards, the teams will compete with 11 players on the field albeit in a shorter time frame. The teams will be divided in four groups of four teams each with the winner of each group progressing to the knockout phase of the tournament.", date : "2020-12-16", prize : 50000, prerequistes : "Each team should contain not more than 11 players.", coordinator : "jehan Mehta", contact : "9886754532", comments : "All teams will receive participation certificates.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Enthusia", title : "Pro Cricket League", description : "Pro Football League is VJTI's professional cricket league. 12 teams from Mumbai’s best colleges will compete in a league-cum-knockout format to be crowned as the inaugural PCL Champions. Not compromising on professional standards, the teams will compete with 11 players on the field albeit in a shorter time frame. The teams will be divided in four groups of four teams each with the winner of each group progressing to the knockout phase of the tournament.", date : "2020-12-17", prize : 50000, prerequistes : "Each team should contain not more than 11 players.", coordinator : "Rehan Shah", contact : "9855754532", comments : "All teams will receive participation certificates.", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Enthusia", title : "Pro Chess League", description : "Chess is a game of the mind. Only resilience and focus can win the game. Are you up for it? Students from 25 colleges all across Maharashtra will participate in this nail biting competition. Register now!!", date : "2020-12-17", prize : 25000, prerequistes : "Should be studying for a registered university.", coordinator : "Vidit Raina", contact : "9567345612", comments : "It will be conducted as a swiss system with 7 rounds.", image_url : "" }); `
        res = await txc.run(query);

        query = `MERGE (e:Event { club_name : "Pratibimb", title : "Poetry Slam", description : "Poetry is when an emotion has found its thought and the thought has found words. So, put that pen down and grab that mic up 'cause we here at VJTI are all ears. VJTI Performing Arts brings to its inter-college Poetry Slam competition _Rhapsody_ which will be judged by Vihaan Goyal. He is a poet, actor, youtuber and a storyteller.  He has worked in several TV shows and took poetry writing and reciting as a way to put this thoughts into words.", date : "2020-12-18", coordinator : "Rugved", contact : "7021672668", image_url : "" });`
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Pratibimb", title : "EDM - Ritviz", description : "Pratibimb VJTI brings to you a live EDM Concert by widely popular and critically acclaimed Hindustani musical prodigy RITVIZ on 22nd December. Registration is mandatory", date : "2020-12-22", coordinator : "Sarah Shah", contact : "8956731156", image_url : "" }); `
        res = await txc.run(query);
        query = `MERGE (e:Event { club_name : "Pratibimb", title : "Open Mic night", description : "'Riffs on life between Cultures in many voices' - Pratibimb is back with the much awaited online edition of Open mic With the world at a standstill and our passion to perform and express at a pinnacle. It's your moment to shine. We invite you to experience an evening dedicated to your love of art♥ Year no bar. Language no bar.", date : "2020-12-19", coordinator : "Yashvi Jain", contact : "9756384657", comments : "Registrations will be carried forward from the open mic planned in March 2020 and we will get in touch with them soon.", image_url : "" });`
        res = await txc.run(query);

        return res;
    });
    session.close();
}